### ISSUE TITLE
using Facebook.Unity on Windows Desktop

### ISSUE THREAD

**Issue by jpetays** [getbraincloud/examples-unity#112]
Line 9 should read:
#if UNITY_WEBGL || UNITY_STANDALONE_WIN
using Facebook.Unity;
#endif

otherwise ConnectScene.cs will not compile when you open the project with default settings (Standalone).
(m_EditorVersion: 2020.3.22f1)

**Comment by unitycoder** [comment]
ok nice, it fixes this error:
`Assets\Scripts\ConnectScene.cs(289,31): error CS0246: The type or namespace name 'ILoginResult' could not be found (are you missing a using directive or an assembly reference?)`
