### ISSUE TITLE
Tutorial needed

### ISSUE THREAD

**Issue by morybest** [getbraincloud/examples-unity#27]
The new BomberRTT is a Gigantic online project that need more tutorial and information . this kind of sample making for a solution is not cover any developers how wanna start work with brain-cloud . Please change your mind about client experience and knowledge.start with a video tutorial is very good start.

**Comment by davidstl** [comment]
Hi, check in the develop branch, we added a RelayTestApp. A much simpler/cleaner example for RTT and Relay.
